version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      
    open-pull-requests-limit: 10

    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"

    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]